export const WITHDRAW = 'WITHDRAW';
export const DEPOSIT = 'DEPOSIT';
export const BUY_VP = 'BUY_VP';

export const WITHDRAW_INPUT_TO_ADDRESS = 'INPUT_TO_ADDRESS';
export const WITHDRAW_INPUT_AMOUNT = 'INPUT_AMOUNT';
export const WITHDRAW_BEFORE_EXECUTE = 'BEFORE_EXECUTE';

export const STORED_ACCESS_TOKEN = 'STORED_ACCESS_TOKEN';
export const NEW_CREATE = 'NEW_CREATE';
export const DEFAULT_WALLET = 'DEFAULT_WALLET';
export const STORED_FCM_TOKEN = 'STORED_FCM_TOKEN';
